---
- name: Create server
  hosts: localhost

  vars: 
    HETZNER_TOKEN: "{{ lookup('env', 'HETZNER_TOKEN') }}"
    HETZNER_TYPE: "cx11"
    HETZNER_NAME: "hryszko.dev"
    SSH_KEY: "simon@hryszko.dev"

  tasks:
    - name: Check if server exist
      hcloud_server_info:
        api_token: "{{ HETZNER_TOKEN }}"
        name: "{{ HETZNER_NAME }}"
      register: server_info

    - name: Debugging
      debug:
        var: server_info

    - name: Create a new instance with an SSH key.
      hetzner.hcloud.hcloud_server:
        api_token: "{{ HETZNER_TOKEN }}"
        name: "{{ HETZNER_NAME }}"
        server_type: "{{ HETZNER_TYPE }}"
        image: ubuntu-20.04
        location: hel1
        ssh_keys:
          - "{{ SSH_KEY }}"
        state: present
      register: instance_data
      when: server_info.hcloud_server_info[0].status == "absent"