---
- name: Create server
  hosts: localhost

  vars: 
    HETZNER_TOKEN: "{{ lookup('env', 'HETZNER_TOKEN') }}"
    HETZNER_TYPE: "{{ lookup('env', 'HETZNER_TYPE') }}"
    HETZNER_NAME: "{{ lookup('env', 'HETZNER_NAME') }}"
    HETZNER_SSH_KEY: "{{ lookup('env', 'HETZNER_SSH_KEY') }}"

  tasks:
    - name: Retrieve server
      hcloud_server_info:
        api_token: "{{ HETZNER_TOKEN }}"
        name: "{{ HETZNER_NAME }}"
      register: server_info

    - name: Create a new instance with an SSH key.
      hetzner.hcloud.hcloud_server:
        api_token: "{{ HETZNER_TOKEN }}"
        name: "{{ HETZNER_NAME }}"
        server_type: "{{ HETZNER_TYPE }}"
        image: ubuntu-20.04
        location: hel1
        HETZNER_SSH_KEYs:
          - "{{ HETZNER_SSH_KEY }}"
        state: present
      register: instance_data
      when: server_info.hcloud_server_info | length == 0