---
- name: Create server
  hosts: localhost

  vars: 
    HETZNER_TOKEN: "{{ lookup('env', 'HETZNER_TOKEN') }}"
    HETZNER_SERVER_TYPE: "{{ lookup('env', 'HETZNER_SERVER_TYPE') }}"
    HETZNER_SERVER_NAME: "{{ lookup('env', 'HETZNER_SERVER_NAME') }}"
    HETZNER_SSH_NAME: "{{ lookup('env', 'HETZNER_SSH_NAME') }}"
    CLOUDFLARE_TOKEN: "{{ lookup('env', 'CLOUDFLARE_TOKEN') }}"

  tasks:
    - name: Retrieve server
      hcloud_server_info:
        api_token: "{{ HETZNER_TOKEN }}"
        name: "{{ HETZNER_SERVER_NAME }}"
      register: server_info

    - name: Create a new instance with an SSH key.
      hetzner.hcloud.hcloud_server:
        api_token: "{{ HETZNER_TOKEN }}"
        name: "{{ HETZNER_SERVER_NAME }}"
        server_type: "{{ HETZNER_SERVER_TYPE }}"
        image: ubuntu-20.04
        location: hel1
        ssh_keys:
          - "{{ HETZNER_SSH_NAME }}"
        state: present
      register: instance_data
      when: server_info.hcloud_server_info | length == 0

    - name: Update CloudFlare DNS records.
      community.general.cloudflare_dns:
        zone: hryszko.dev
        record: engelbart
        type: A
        value: "{{ instance_data.hcloud_server.ipv4_address }}"
        solo: yes
        account_email: Szevaa.97@gmail.com
        api_token: "{{ CLOUDFLARE_TOKEN }}"
      register: record
      when: instance_data.hcloud_server.ipv4_address is defined