---
- name: Add server IP to group
  hosts: localhost

  vars: 
    HETZNER_TOKEN: "{{ lookup('env', 'HETZNER_TOKEN') }}"
    HETZNER_NAME: "{{ lookup('env', 'HETZNER_NAME') }}"

  tasks:
    - name: Retrieve server
      hcloud_server_info:
        api_token: "{{ HETZNER_TOKEN }}"
        name: "{{ HETZNER_NAME }}"
      register: server_info

    - name: Add retrieved IP to group
      add_host:
        name: "{{ server_info.hcloud_server_info[0].ipv4_address }}"
        groups: servers

- name: Manage server
  hosts: servers
  remote_user: root

  tasks:
    - name: wait for connection
      wait_for_connection:
      
    - name: install ranger
      apt:
        name: 
        - ranger
        - git
        - curl
        - vim
        state: latest
        update_cache: yes

    - name: Make docker group
      group:
        name: docker

    - name: Add new user called simon
      user:
        name: simon
        state: present
        groups:
          - sudo
          - docker
        shell: /bin/bash
        home: /home/simon

    - name: Make /home/simon/.ssh dir
      file:
        path: /home/simon/.ssh
        state: directory
        owner: simon

    - name: Copy root ssh key to new user
      copy:
        src: /root/.ssh/authorized_keys
        dest: /home/simon/.ssh/authorized_keys
        owner: simon
        mode: 0600
        remote_src: yes
        follow: yes

    - name: Run shell command
      shell: echo "#\!/bin/bash\nexport PS1='[\[\e[32m\]\u\[\e[m\]@\[\e[35m\]\h\[\e[m\]] \[\e[31m\]\w\[\e[m\] \[\e[32m\]⇨\[\e[m\]  '" > /home/simon/.bashrc && curl https://raw.githubusercontent.com/Shirobachi/dot-files/main/.aliases | grep -e 'alias\|export' >> /home/simon/.bashrc