---
- name: Manage server
  hosts: servers
  remote_user: root

  tasks:
    - name: wait for connection
      wait_for_connection:
      
    - name: install ranger
      apt:
        name: 
        - ranger
        - git
        - curl
        - vim
        state: latest
        update_cache: yes
        upgrade: yes