---
- name: Manage server
  hosts: servers
  remote_user: root

  tasks:
    - name: install ranger
      apt:
        name: 
        - ranger
        - git
        - curl
        - vim
        state: latest
        update_cache: yes
        upgrade: yes
        require:
          - wait_for_connection