---
- name: Add server to hosts
  hosts: localhost
  
  vars: 
    HETZNER_TOKEN: "{{ lookup('env', 'HETZNER_TOKEN') }}"
    HETZNER_NAME: "{{ lookup('env', 'HETZNER_NAME') }}"
  
  tasks:
    - name: Add host to inventory.
      add_host:
        name: "engelbart.hryszko.dev"
        groups: servers

- name: Manage server
  hosts: servers
  remote_user: root
  gather_facts: False

  tasks:
    - name: Wait for connection.
      wait_for_connection:

    - name: install ranger
      apt:
        name: 
        - ranger
        - git
        - curl
        - vim
        state: latest
        update_cache: yes
        upgrade: yes
        require:
          - wait_for_connection