name: Run ansible playbook

on:
  push:
  workflow_dispatch:

env: 
  HETZNER_TOKEN: ${{ secrets.HETZNER_TOKEN }}
  HETZNER_TYPE: cx11
  HETZNER_NAME: hryszko.dev
  SSH_KEY: simon@hryszko.dev

jobs:
  create-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Ansible Galaxy collections
        run:  ansible-galaxy collection install hetzner.hcloud community.general

      - name: Install dependencies
        run: pip3 install python-dateutil hcloud 
        
      - name: Upgrade ansible
        run: pip3 install --upgrade ansible
        
      - name: Set up SSH-Agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Create server
        run: ansible-playbook playbooks/create_server.yml
        env:
          HETZNER_TOKEN: ${{ env.HETZNER_TOKEN }}
          HETZNER_TYPE: ${{ env.HETZNER_TYPE }}
          HETZNER_NAME: ${{ env.HETZNER_NAME }}
          SSH_KEY: ${{ env.SSH_KEY }}