name: Run ansible playbook

on:
  push:
  workflow_dispatch:

jobs:
  create-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Ansible Galaxy collections
        run:  ansible-galaxy collection install hetzner.hcloud community.general

      - name: Install dependencies
        run: pip3 install python-dateutil hcloud 
        
      - name: Install dependencies
        run: pip3 install --upgrade ansible
        
      - name: Run Ansible Playbook
        run: ansible-playbook playbooks/create_server.yml
        env:
          HETZNER_TOKEN: ${{ secrets.HETZNER_TOKEN }}