name: Run ansible playbook

on:
  push:
  workflow_dispatch:

jobs:
  create-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Ansible Galaxy collections
        run:  ansible-galaxy collection install hetzner.hcloud community.general

      - name: Install dependencies
        run: pip3 install python-dateutil hcloud 
        
      - name: Upgrade ansible
        run: pip3 install --upgrade ansible
        
      - name: Set up SSH-Agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Create server
        run: ansible-playbook playbooks/create_server.yml
        env:
          HETZNER_TOKEN: ${{ secrets.HETZNER_TOKEN }}