name: Run ansible playbook

on:
  push:
  workflow_dispatch:

env: 
  HETZNER_TOKEN: ${{ secrets.HETZNER_TOKEN }}
  HETZNER_TYPE: cx11
  HETZNER_NAME: hryszko.dev
  HETZNER_SSH_KEY: simon@hryszko.dev
  SSH_KEY_PRV: ${{ secrets.SSH_KEY }}

jobs:
  set-up-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Ansible Galaxy collections
        run:  ansible-galaxy collection install hetzner.hcloud community.general

      - name: Install dependencies
        run: pip3 install python-dateutil hcloud 
        
      - name: Upgrade ansible
        run: pip3 install --upgrade ansible
        
      - name: make ssh file
        run: echo "{{ SSH_KEY_PRV }}" > ssh_key

      - name: chmod ssh key file
        run: chmod 600 ssh_key

      - name: Set up SSH-Agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: "${{ env.SSH_KEY_PRV }}"

      - name: Create server
        run: ansible-playbook playbooks/create_server.yml
        env:
          HETZNER_TOKEN: ${{ env.HETZNER_TOKEN }}
          HETZNER_TYPE: ${{ env.HETZNER_TYPE }}
          HETZNER_NAME: ${{ env.HETZNER_NAME }}
          HETZNER_SSH_KEY: ${{ env.HETZNER_SSH_KEY }}

      - name: test connection
        run: ansible -m ping all -vv

      - name: Manage server
        run: ansible-playbook playbooks/manage_server.yml
        env:
          HETZNER_TOKEN: ${{ env.HETZNER_TOKEN }}
          HETZNER_NAME: ${{ env.HETZNER_NAME }}