name: Run ansible playbook

on:
  push:
  workflow_dispatch:

env: 
  HETZNER_TOKEN: ${{ secrets.HETZNER_TOKEN }}
  HETZNER_TYPE: cx11
  HETZNER_NAME: hryszko.dev
  HETZNER_SSH_KEY: simon@hryszko.dev
  SSH_KEY_PRV: ${{ secrets.SSH_KEY }}
  CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  set-up-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Ansible Galaxy collections
        run:  ansible-galaxy collection install hetzner.hcloud community.general

      - name: Install dependencies
        run: pip3 install python-dateutil hcloud 
        
      - name: Upgrade ansible
        run: pip3 install --upgrade ansible

      - name: Create server
        run: ansible-playbook playbooks/create_server.yml
        env:
          HETZNER_TOKEN: ${{ env.HETZNER_TOKEN }}
          HETZNER_TYPE: ${{ env.HETZNER_TYPE }}
          HETZNER_NAME: ${{ env.HETZNER_NAME }}
          HETZNER_SSH_KEY: ${{ env.HETZNER_SSH_KEY }}
          CLOUDFLARE_TOKEN: ${{ env.CLOUDFLARE_TOKEN }}

      - name: set up SSH-key
        run: mkdir ~/.ssh && echo "${{ env.SSH_KEY_PRV }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: Manage server
        run: ansible-playbook playbooks/manage_server.yml
        env:
          HETZNER_TOKEN: ${{ env.HETZNER_TOKEN }}
          HETZNER_NAME: ${{ env.HETZNER_NAME }}
          PASSWORD: ${{ env.PASSWORD }}